### ISSUE TITLE
Invalid component selector when importing blocks

### ISSUE THREAD

**Issue by jedmao** [necolas/postcss-bem-linter#48]
Using [postcss-import](https://github.com/postcss/postcss-import), which might be the root of the problem, I have a file that imports two blocks from separate CSS files like so:

```css
@import block1;
@import block2;
```

Here are the contents of block1:

```css
/** @define block1 */

.block1 {
    color: red;
}
```

And here are the contents of block2:

```css
/** @define block2 */

.block2 {
    color: blue;
}
```

These, of course, get merged into one file with the imports, which is throwing an "Invalid component selector" error. postcss-bem-linter, expects only one block per file, but it sees them combined into one file, like so:

```css
/** @define block1 */

.block1 {
    color: red;
}

/** @define block2 */

.block2 {
    color: blue;
}
```

Perhaps an option that allows one to have multiple blocks per file would resolve this issue? What do you think?
